server:
  port: 8443
  servlet:
    context-path: /clinic
  ssl:
    key-store: ${KEY_STORE}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: ${KEY_STORE_TYPE}
    key-alias: ${KEY_ALIAS}
    key-password: ${KEY_PASSWORD}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/system_kliniki_medycznej
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

project:
  default-image: doctors/default_profile_image.webp
  doctor: doctors/
  patients: patients/

base:
  url: "https://localhost:8443/clinic/"

logging:
  level:
    org.springframework.web.reactive.function.client.WebClient: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.security: DEBUG
    org.springframework: DEBUG

secret.key: ${SECRET_KEY}
