server:
  port: 8080
  servlet:
    context-path: /clinic
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/system_kliniki_medycznej
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
