insert into category(name)
values ('Wybrane choroby zakaźne i pasożytnicze'),
       ('Nowotwory'),
       ('Choroby krwi i narządów krwiotwórczych oraz wybrane choroby przebiegające z udziałem mechanizmów immunologicznych'),
       ('Zaburzenia wydzielania wewnętrznego, stanu odżywienia i przemian metabolicznych'),
       ('Zaburzenia psychiczne i zaburzenia zachowania'),
       ('Choroby układu nerwowego'),
       ('Choroby oka i przydatków oka'),
       ('Choroby ucha i wyrostka sutkowatego'),
       ('Choroby układu krążenia'),
       ('Choroby układu oddechowego'),
       ('Choroby układu pokarmowego'),
       ('Choroby skóry i tkanki podskórnej'),
       ('Choroby układu mięśniowo-szkieletowego i tkanki łącznej'),
       ('Choroby układu moczowo-płciowego'),
       ('Ciąża, poród i okres połogu'),
       ('Wybrane stany rozpoczynające się w okresie okołoporodowym'),
       ('Wady rozwojowe wrodzone, zniekształcenia i aberracje chromosomowe'),
       ('Objawy, cechy chorobowe oraz nieprawidłowe wyniki badań klinicznych i laboratoryjnych niesklasyfikowane gdzie indziej'),
       ('Urazy, zatrucia i inne określone skutki działania czynników zewnętrznych'),
       ('Zewnętrzne przyczyny zachorowania i zgonu'),
       ('Czynniki wpływające na stan zdrowia i kontakt ze służbą zdrowia'),
       ('Kody do celów specjalnych');